### PR TITLE
Don't let min/max go outside int8 range

### PR DESCRIPTION
**Pull request by a1k0n**
I was seeing some waveforms crossing over oddly; this fixes that.

### CODE REVIEW

**Comment by oncletom** [comment]
Thanks @a1k0n :-)

How can I reproduce this edge case? I suppose this is due to a float number slightly below -127 (like -127.000001) or slightly above 128 (like  128.000001)?

**Comment by a1k0n** [comment]
Well, it's pretty easy to reproduce by loading up a pretty loud track or by messing with options.scale / scale_adjuster. It's not really just an edge case; sorry, my comment didn't really do it justice. What's happening is that the value is wrapping when being cast to an int8, so if the max is > 127 it will wrap around to -128 and above, and vice versa for min.

I was seeing all kinds of waves crossing over when rendering the waveform as a polygon, which is what led to this PR.

**Comment by a1k0n** [comment]
Sorry, my explanation above isn't very illuminating.

An illustration of what led to this PR: screenshot 2015-03-11 12 15 20

This is the 8-bit integer truncation I am trying to prevent in this PR:
```javascript
> x = new Int8Array(3)
> [0, 0, 0]
> x[0] = 127
> x[1] = 128
> x[2] = 129
> x
[127, -128, -127]
```

**Comment by oncletom** [comment]
Okay it makes sense — I roughly got what you said but now the picture makes it is crystal clear, thanks!

**Comment by oncletom** [comment]
Made available in `v1.5.1`:-)

**Pull request merged**
